# Setup
title:               Maybe's blog
url:                 http://ztng123.github.io
baseurl:             ''
paginate:            5
permalink:           pretty


# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
