# Setup
title:               Maybe's blog
url:                 https://ztng123.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
social_email: dpwl991102@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
